CREATE TABLE users (
	id SERIAL PRIMARY KEY,
	firstName VARCHAR(50) NOT NULL,
	lastName VARCHAR(50) NOT NULL,
	email VARCHAR(100) UNIQUE NOT NULL,
	birthdate DATE NOT NULL,
	createDate TIMESTAMP DEFAULT NOW()
);